### ISSUE TITLE
Merge latest upstream Kernel/Spectre fixes.

### ISSUE THREAD

**Issue by BtbN** [Alberto97/android_kernel_motorola_msm8953#1]
How realistic is it to get this Kernel up to date with latest upstream Linux 3.18.91, and potentially even add the backported Spectre(/Meltdown?) patches from Googles fork, if they don't hit upstream by then?

https://android.googlesource.com/kernel/common/+log/android-3.18

I tried just merging 3.18.91 (https://github.com/BtbN/android_kernel_motorola_msm8953/tree/mergework), and after some conflict resolution, it went relatively smoothly, but the resulting Kernel does not boot and I was unable to debug it properly.

**Comment by adekmaulana** [comment]
A53 CPU doesn't effect on Meltdown
https://en.wikipedia.org/wiki/Meltdown_(security_vulnerability)

**Comment by BtbN** [comment]
Meltdown is an Intel x86 specific bug. But Spectre does affect all CPUs, including ARM.
However, according to ARM themselves, the SoC in question is not affected by it, for whatever reason.

Getting up to date would still be nice, as there are tons of other security fixes in there.

**Comment by Alberto97** [comment]
I'm sorry but kernel upgrades are too much time consuming and most of the stuff does not generally apply to Android or arm.
