### ISSUE TITLE
Moto-Wifi-Mac lost after latest updates(OPN28)

### ISSUE THREAD

**Issue by BtbN** [Alberto97/android_kernel_motorola_msm8953#3]
Did some digging as to why this happened, and traced it back to this return being added when comparing the two branches:

https://github.com/Alberto97/android_kernel_motorola_msm8953/blob/oreo-mr1/drivers/staging/prima/CORE/VOSS/src/vos_nvitem.c#L1807

Now, the mac pointer clearly is NULL in this invocation:
https://github.com/Alberto97/android_kernel_motorola_msm8953/blob/oreo-mr1/drivers/staging/prima/CORE/VOSS/src/vos_nvitem.c#L1440

The code is ok with it being NULL when the Moto-Define is enabled, so my proposed fix:
https://github.com/BtbN/android_kernel_motorola_msm8953/commit/a5e00e590bdda808431f833f48903703190a3dcf

**Comment by Alberto97** [comment]
Yeah, my fault, I fixed this yesterday but I should have checked moto's prima repo before rebasing, in fact they had a fix for this which is quite similar to yours (https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-wlan-prima/commit/ef5642937b67b98de1de2102b0421eab1c4b218b).
Thank you anyway for proposing a fix :)
